
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=DC36395645F95A096651D99DE08C4B59

;GAS 디버그용 설정
[/Script/GameplayAbilities.AbilitySystemGlobals]
;bUseDebugTargetFromHud=true